### ISSUE TITLE
Wrong order of extracted keywords

### ISSUE THREAD

**Issue by CharlesGaydon** [bguvenc/keyword_extraction#2]
Hello,
thanks for the code. 
I want to point out that the bottom-n terms are extracted and not the top-n terms, as argsort sorts in ascending order.
To reverse this behavior, see : 
https://stackoverflow.com/questions/16486252/is-it-possible-to-use-argsort-in-descending-order

I am considering forking and correcting this myself, alongside other functionnalities (such as accepting phrases instead of single words as input) but I will probably not have the time :)

**Comment by CharlesGaydon** [comment]
@bguvenc juste "uppig" this issue in case you had not seen it.

**Comment by dhiahassen** [comment]
upping again

**Comment by dhiahassen** [comment]
@CharlesGaydon  They closed the issue

**Comment by CharlesGaydon** [comment]
I can only imagine that it has been solved then. I used this repo a long time ago, so I guess I'll leave it to be.
